### ISSUE TITLE
Extending the Spec: Discussion

### ISSUE THREAD

**Issue by przell** [Terradue/stac-extensions-disaster#1]
Dear @emmanuelmathot, 
We have a project about mutli-hazards and describing them with EO and climate data. Our aim would be to link an event/impact with it’s extent and timing to different EO/climate datasets so that the user can directly extract the related information. At Eurac we’re responsible for building an Event/Impact Data base. 

Does that sound like something that could be integrated into the disaster spec, or does it sound like a new spec? I could propose to describe an event with the existing spec and suggest some additions we would need.

All the best, 
Peter

**Comment by emmanuelmathot** [comment]
Hello Peter. Thank you for your interest in our stac extension.
Indeed, this extesnion is dedicated to specifying items of the [Disaster Charter](https://disasterscharter.org/). It won't be extended with additional metadata unless it is part of the charter data model.
Anyway, the extension can be resused to other use cases like common fields such as disaster:types or [the best practices](https://github.com/Terradue/stac-extensions-disaster#other-extensions-and-specifications).
From what you tell, we could also have a specific extension dedicated to "events" allowing to link an item with them.
Keep us updated about your work, we are very interested in similar project.
